import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased relative`}>
        <div className="top-0 left-0 absolute font-['offbit-dot'] uppercase text-sm font-bold tracking-wide px-5 pt-3 z-50 bg-zinc-950 text-white flex items-center justify-between w-full">
          {/* left navbar */}
          <Link href={"/"} className="text-lg">Yeshu Agarwal</Link>
          {/* right nav */}
          <div className="flex items-center gap-5 uppercase">
            <Link href={""}>Blog</Link>
            <Link href={""}>Contact</Link>
            <Link href={""}>Linkedin</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
